### ISSUE TITLE
Unable to build due to TBB. 

### ISSUE THREAD

**Issue by kratosaba** [nathanrgodwin/overfit-shapes#3]
I'm trying to use build your code, I installed all the dependencies inside a google colab VM(its OS is Ubuntu). However I keep getting this issue. You recommend to have TBB >=4 could you specify which one you mean?

![image](https://user-images.githubusercontent.com/32924782/102144744-a3598180-3e2b-11eb-9941-6dc4f509d1f9.png)

I ran the following:

![image](https://user-images.githubusercontent.com/32924782/102146043-f3394800-3e2d-11eb-9eb8-45f6582f9d91.png)

And: 

![image](https://user-images.githubusercontent.com/32924782/102146232-372c4d00-3e2e-11eb-9baa-9f304994d235.png).

Would you be able to point me to a direction that I could build your code in ubuntu?

**Comment by nathanrgodwin** [comment]
I haven't tried building this on Linux in a while, but an earlier version did work. The error means that CMake can't find TBB. Try to find the directory in your TBB install containing the file TBBConfig.cmake (usually this is [TBB install location]/lib/cmake/) and run the CMake command:

cmake .. -DTBB_DIR="[PATH TO TBBConfig.cmake DIRECTORY]"

This will tell CMake where to look for the TBB installation.

**Comment by kratosaba** [comment]
> I haven't tried building this on Linux in a while, but an earlier version did work. The error means that CMake can't find TBB. Try to find the directory in your TBB install containing the file TBBConfig.cmake (usually this is [TBB install location]/lib/cmake/) and run the CMake command:
> 
> cmake .. -DTBB_DIR="[PATH TO TBBConfig.cmake DIRECTORY]"
> 
> This will tell CMake where to look for the TBB installation.

Yes I think the VM is missing the TBBConfig.cmake file. I decided to clone this repository("https://github.com/wjakob/tbb.git") and build it, and I was able to add get the TBBConfig file. Then I  gave the path to the cmake command. It seems this still doesn't work. Thank you for the reply, but I can't seem to make it work in google colab. I will try and implement the sampler by myself.

**Comment by z-hasher** [comment]
Just a comment about getting around with the error above. So if you've installed TBB and you don't see any `FindTBB.cmake` or any cmake Config file, then just comment out the `find_package(TBB)`, instead, do (my example is that my tbb is installed under /usr)
```
find_path(TBB_INCLUDE_DIR "tbb/tbb.h" "/usr/include")
find_library(TBB_LIBRARIES NAMES tbb tbbmalloc HINTS "/usr/lib/x86_64-linux-gnu")
```
And for any target that links against `TBB::tbb`, replace it with `${TBB_LIBRARIES}`. And for that target, you will also manually include TBB headers. For instance
```
target_include_directories(FastWindingNumbers PUBLIC ${TBB_INCLUDE_DIR})
```
Not that this is not guaranteed to work for you. This works for me on Ubuntu 16.

**Comment by nathanrgodwin** [comment]
This should work in general if you don't have TBBConfig.cmake. I'm guessing the TBB version in the apt package list doesn't have this included.

TBBConfig.cmake essentially wraps the above commands in a namespace TBB::tbb and includes them when you link against that namespace.
