### ISSUE TITLE
Please check the windingNumber in 3rdParty

### ISSUE THREAD

**Issue by LS33** [nathanrgodwin/overfit-shapes#4]
hi, i just clone your code by git clone --recursive, but i find that the windingnumber folder has nothing there. please check this. Thank!

**Comment by nathanrgodwin** [comment]
Hi, thanks for bringing this to my attention. It does look like the submodule linkage got broken somehow. It should be fixed with the latest commit.

**Comment by LS33** [comment]
thanks for your quick answer, i guess i successfully build this.
